name = "start"
compatibility_date = "2024-12-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "test"
database_id = "cfcc5677-2d27-412e-a7ff-f49073269ccd"

[[kv_namespaces]]
binding = "KV"
id = "ad13af1682b74a2f9c872b956423401c"

[vars]
JWT_SECRET = "starhub-jwt-secret-x7k9m2p4q8w1"
