/**
 * /api/classic/room/:code — Room details
 *
 * GET /api/classic/room/:code — Get room details with KV caching (10s TTL)
 *
 * Validates: Requirements 6.1, 16.2, 16.4
 */

import { jsonResponse, errorResponse } from '../../_lib/db';

interface Env {
  DB: D1Database;
  KV: KVNamespace;
  JWT_SECRET: string;
  GAME_ROOM: DurableObjectNamespace;
}

const KV_TTL_SECONDS = 10;
const ROOM_CODE_PATTERN = /^[A-Z0-9]{6}$/;

export const onRequestGet: PagesFunction<Env> = async (context) => {
  const code = context.params.code as string;

  if (!code || !ROOM_CODE_PATTERN.test(code)) {
    return errorResponse('Invalid room code: must be 6 alphanumeric characters [A-Z0-9]', 400);
  }

  const { KV, GAME_ROOM } = context.env;
  const kvKey = `room:${code}:info`;

  // Check KV cache first
  const cached = await KV.get(kvKey);
  if (cached) {
    try {
      const roomInfo = JSON.parse(cached);
      return jsonResponse({ ...roomInfo, cached: true });
    } catch {
      // Cache corrupted, fall through
    }
  }

  // Look up the DO by room code.
  // Since room codes are generated by the DO itself, we need a way to map
  // code → DO ID. We use a KV lookup key set during room creation.
  const doIdStr = await KV.get(`room:${code}:doId`);
  if (!doIdStr) {
    return errorResponse('Room not found', 404);
  }

  let doId: DurableObjectId;
  try {
    doId = GAME_ROOM.idFromString(doIdStr);
  } catch {
    return errorResponse('Room not found', 404);
  }

  const stub = GAME_ROOM.get(doId);

  // Forward to the DO's /info endpoint
  const infoResponse = await stub.fetch('https://do/info');
  if (!infoResponse.ok) {
    return errorResponse('Failed to fetch room details', 502);
  }

  const roomInfo = await infoResponse.json();

  // Cache the response in KV
  await KV.put(kvKey, JSON.stringify(roomInfo), { expirationTtl: KV_TTL_SECONDS });

  return jsonResponse({ ...(roomInfo as Record<string, unknown>), cached: false });
};
